"use client";

import Link from "next/link";
import { ArrowRight, Clock3, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import { languageFromStorage, type EasyTLanguage } from "@/lib/easyt/i18n";
import styles from "./home-explorer.module.css";

const routes = [
  { place: "Japan", title: ["Japan, one good day at a time", "Japón, un buen día a la vez"], detail: ["Tokyo energy, mountain towns and enough room for a meal to change the plan.", "La energía de Tokio, pueblos de montaña y espacio para que una comida cambie el plan."], image: "/journey/japan-evening-route.jpg", href: "/journey/routes/japan-slow", tag: ["Asia · 10 days", "Asia · 10 días"], bases: "Tokyo · Takayama · Kyoto" },
  { place: "Portugal", title: ["The Atlantic reset", "Un descanso junto al Atlántico"], detail: ["Lisbon energy, a quiet coast and nothing booked too tightly.", "La energía de Lisboa, una costa tranquila y nada reservado con demasiada rigidez."], image: "/journey/portugal-atlantic-route.jpg", href: "/journey/routes/portugal-coast", tag: ["Europe · 7 days", "Europa · 7 días"], bases: "Lisboa · Comporta · Lagos" },
  { place: "Peru", title: ["Andean highlands, gently", "Las alturas andinas, sin prisa"], detail: ["Acclimatise, take the Sacred Valley slowly, then choose your big day.", "Aclimátate, recorre el Valle Sagrado con calma y luego elige tu gran día."], image: "/journey/peru-sacred-valley-route.jpg", href: "/journey/routes/andean-highlands", tag: ["South America · 9 days", "Sudamérica · 9 días"], bases: "Cusco · Valle Sagrado · Arequipa" },
  { place: "Taiwan", title: ["Taiwan by train", "Taiwán en tren"], detail: ["Night markets, tea hills and an easy rail route south.", "Mercados nocturnos, colinas de té y una sencilla ruta en tren hacia el sur."], image: "/journey/taiwan-rail-route.jpg", href: "/journey/routes/taiwan-rail", tag: ["Asia · 8 days", "Asia · 8 días"], bases: "Taipéi · Taichung · Tainan" },
];

const copy = { en: { eyebrow: "Start with a good idea", title: "Choose a route with a point of view.", featured: "Featured route", bases: "Bases", call: "Your call", editable: "Change any stop, day or suggestion", build: "Build this route", open: "Open route", blank: "Want a completely blank canvas?", scratch: "Start a trip from scratch", browse: "Browse all routes" }, es: { eyebrow: "Empieza con una buena idea", title: "Elige una ruta con una mirada propia.", featured: "Ruta destacada", bases: "Bases", call: "Tú decides", editable: "Cambia cualquier parada, día o sugerencia", build: "Crea esta ruta", open: "Abrir ruta", blank: "¿Quieres empezar con un lienzo totalmente en blanco?", scratch: "Empieza un viaje desde cero", browse: "Ver todas las rutas" } } as const;

export default function InspirationExplorer() {
  const [language, setLanguage] = useState<EasyTLanguage>("en");
  useEffect(() => { setLanguage(languageFromStorage()); const update = (event: Event) => setLanguage((event as CustomEvent<EasyTLanguage>).detail); window.addEventListener("easyt-language-change", update); return () => window.removeEventListener("easyt-language-change", update); }, []);
  const index = language === "es" ? 1 : 0; const text = copy[language]; const [featured, ...moreRoutes] = routes;
  return <section className={styles.explorer} id="routes"><header className={styles.explorerHead}><div><p className={styles.eyebrow}>{text.eyebrow}</p><h2>{text.title}</h2></div><Link className={styles.browseLink} href="/journey/discover">{text.browse} <ArrowRight aria-hidden="true" /></Link></header><Link className={styles.featuredRoute} href={featured.href}><div className={styles.featuredImage} style={{ backgroundImage: `url(${featured.image})` }}><span>{featured.place}</span><small>{featured.tag[index]}</small></div><div className={styles.featuredCopy}><p>{text.featured}</p><h3>{featured.title[index]}</h3><span>{featured.detail[index]}</span><dl><div><dt><MapPin aria-hidden="true" /> {text.bases}</dt><dd>{featured.bases}</dd></div><div><dt><Clock3 aria-hidden="true" /> {text.call}</dt><dd>{text.editable}</dd></div></dl><b>{text.build} <ArrowRight aria-hidden="true" /></b></div></Link><div className={styles.routeGrid}>{moreRoutes.map((route) => <Link className={styles.routeCard} key={route.place} href={route.href}><div className={styles.routeImage} style={{ backgroundImage: `url(${route.image})` }}><span>{route.tag[index]}</span></div><div><small>{route.place}</small><strong>{route.title[index]}</strong><p>{route.detail[index]}</p><i>{text.open} <ArrowRight aria-hidden="true" /></i></div></Link>)}</div><p className={styles.routeFooter}>{text.blank} <Link href="/journey/new">{text.scratch} <ArrowRight aria-hidden="true" /></Link> · <Link href="/journey/discover">{text.browse} <ArrowRight aria-hidden="true" /></Link></p></section>;
}
