"use client";

import { useEffect, useState } from "react";
import { languageFromStorage, type EasyTLanguage } from "@/lib/easyt/i18n";
import styles from "./product-shots.module.css";

const copy = {
  en: { eyebrow: "EasyT in motion", title: "A useful trip companion, not just a plan.", aria: "EasyT mobile features", next: "Show next feature", screens: [["Map plan","Plan on the move","The whole day, in your hand.","See the route, today’s plan and nearby options in one calm mobile view."],["Shape time","Make room","Give each place the time it deserves.","Move a slider and EasyT reshapes the route without losing the rhythm of the trip."],["Find nearby","In the moment","Find the right place for right now.","Ask for a meal or a stay near you, then choose from real nearby places without leaving the day’s plan."],["Travel profile","Made for you","A trip that starts with how you travel.","Set your pace, priorities and comfort level once. EasyT uses them as a thoughtful starting point for every new route."],["Stamps","Remember it","Keep the places that changed you.","Build a personal record of the countries and moments you want to keep close."]] },
  es: { eyebrow: "EasyT en movimiento", title: "Un compañero de viaje útil, no solo un plan.", aria: "Funciones móviles de EasyT", next: "Ver la siguiente función", screens: [["Plan de mapa","Planifica en movimiento","Todo el día, en tu mano.","Ve la ruta, el plan de hoy y las opciones cercanas en una sola vista móvil."],["Organizar el tiempo","Haz espacio","Da a cada lugar el tiempo que merece.","Mueve un control y EasyT reajusta la ruta sin perder el ritmo del viaje."],["Buscar cerca","En el momento","Encuentra el lugar ideal ahora mismo.","Busca una comida o alojamiento cerca y elige lugares reales sin salir del plan del día."],["Perfil de viaje","Hecho para ti","Un viaje que empieza con tu forma de viajar.","Configura una vez tu ritmo, prioridades y nivel de comodidad. EasyT los usa como punto de partida para cada ruta."],["Sellos","Recuérdalo","Guarda los lugares que te cambiaron.","Crea un registro personal de los países y momentos que quieres conservar."]] },
} as const;
const images = ["/journey/product-shots/map-plan-mobile.jpeg","/journey/product-shots/time-mobile.jpeg","/journey/product-shots/finder-mobile.jpeg","/journey/product-shots/profile-mobile.jpeg","/journey/product-shots/stamps-mobile.jpeg"];
const alts = { en: ["EasyT map plan on a phone","EasyT time allocation on a phone","EasyT nearby finder on a phone","EasyT travel profile on a phone","EasyT Stamps map on a phone"], es: ["Plan de mapa de EasyT en un teléfono","Distribución de tiempo de EasyT en un teléfono","Buscador cercano de EasyT en un teléfono","Perfil de viaje de EasyT en un teléfono","Mapa de sellos de EasyT en un teléfono"] } as const;

export default function ProductShowcase() {
  const [language, setLanguage] = useState<EasyTLanguage>("en"); const [active, setActive] = useState(0);
  useEffect(() => { setLanguage(languageFromStorage()); const update = (event: Event) => setLanguage((event as CustomEvent<EasyTLanguage>).detail); window.addEventListener("easyt-language-change", update); return () => window.removeEventListener("easyt-language-change", update); }, []);
  const text = copy[language]; const screen = text.screens[active];
  return <section className={styles.section} aria-label={text.aria}><div className={styles.showcase}><div className={styles.device}><div className={styles.speaker} /><div className={styles.screen}><img src={images[active]} alt={alts[language][active]} /></div></div><div className={styles.copy}><small>{screen[1]}</small><h3>{screen[2]}</h3><p>{screen[3]}</p><div className={styles.picker} role="group" aria-label={text.aria}>{text.screens.map((item, index) => <button type="button" aria-pressed={active === index} className={active === index ? styles.active : ""} onClick={() => setActive(index)} key={item[0]}>{item[0]}</button>)}</div></div></div></section>;
}
