"use client";

import { ArrowUpRight, LocateFixed, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import { languageFromStorage, type EasyTLanguage } from "@/lib/easyt/i18n";
import styles from "./home.module.css";

type Place = { id: string; name: string; address: string; coordinates: [number, number]; mapsUrl: string };
const copy = { en: { food: "Food", stay: "A place to stay", looking: "I’m looking for", want: "Right now, I want", options: ["A quick bite", "One free hour", "A rainy plan", "An easy evening"], moments: ["Right now", "One free hour", "Rainy afternoon", "After a long day"], prompts: ["A good place close to where you are.", "A quick stop with no long detour.", "Somewhere easy to reach and linger indoors.", "Keep it close, uncomplicated and worth it."], stayPrompt: "A nearby place to land tonight, without sending you across town.", finding: "Finding places near you…", findFood: "Find food near me", findStays: "Find stays near me", nearby: "Near you", placeToStay: "A place to stay", results: "OpenStreetMap results", again: "Search again", locationOff: "Location is off.", locationHelp: "Allow location access in your browser, then we can search the places around you.", retry: "Try again", empty: "We could not find matching places nearby. Try another option or move the map.", privacy: "Your location is used only for this search." }, es: { food: "Comida", stay: "Un lugar donde dormir", looking: "Estoy buscando", want: "Ahora quiero", options: ["Algo rápido", "Una hora libre", "Un plan con lluvia", "Una tarde fácil"], moments: ["Ahora mismo", "Una hora libre", "Tarde lluviosa", "Después de un día largo"], prompts: ["Un buen lugar cerca de donde estás.", "Una parada rápida sin un gran desvío.", "Un lugar fácil de llegar y para quedarte bajo techo.", "Cerca, sencillo y que valga la pena."], stayPrompt: "Un lugar cercano para pasar la noche sin cruzar toda la ciudad.", finding: "Buscando lugares cerca de ti…", findFood: "Buscar comida cerca", findStays: "Buscar alojamiento cerca", nearby: "Cerca de ti", placeToStay: "Un lugar donde dormir", results: "Resultados de OpenStreetMap", again: "Buscar de nuevo", locationOff: "La ubicación está desactivada.", locationHelp: "Permite el acceso a la ubicación en tu navegador y buscaremos lugares a tu alrededor.", retry: "Intentar de nuevo", empty: "No encontramos lugares que coincidan cerca. Prueba otra opción o mueve el mapa.", privacy: "Tu ubicación solo se usa para esta búsqueda." } } as const;

export default function HomeRestaurantFinder() {
  const [state, setState] = useState<"idle" | "loading" | "ready" | "empty" | "location">("idle"); const [places, setPlaces] = useState<Place[]>([]); const [moment, setMoment] = useState(0); const [kind, setKind] = useState<"restaurant" | "stay">("restaurant"); const [language, setLanguage] = useState<EasyTLanguage>("en");
  useEffect(() => { setLanguage(languageFromStorage()); const update = (event: Event) => setLanguage((event as CustomEvent<EasyTLanguage>).detail); window.addEventListener("easyt-language-change", update); return () => window.removeEventListener("easyt-language-change", update); }, []);
  const text = copy[language]; const prompt = kind === "stay" ? text.stayPrompt : text.prompts[moment];
  const findNearby = () => { if (!navigator.geolocation) { setState("location"); return; } setState("loading"); navigator.geolocation.getCurrentPosition(async ({ coords }) => { try { const response = await fetch(`/api/journey-local-search?kind=${kind}&city=your%20location&country=&lat=${coords.latitude}&lon=${coords.longitude}`); const data = await response.json() as { places?: Place[] }; setPlaces((data.places ?? []).slice(0, 3)); setState(data.places?.length ? "ready" : "empty"); } catch { setState("empty"); } }, () => setState("location"), { enableHighAccuracy: false, timeout: 8000 }); };
  if (state === "ready") return <div className={styles.homeResults}><p><span>{text.nearby.toUpperCase()} · {kind === "stay" ? text.placeToStay.toUpperCase() : text.moments[moment].toUpperCase()}</span><b>{text.results}</b></p><small className={styles.momentCopy}>{prompt}</small>{places.map((place) => <a href={place.mapsUrl} target="_blank" rel="noreferrer" key={place.id}><span><strong>{place.name}</strong><small><MapPin aria-hidden="true" /> {place.address}</small></span><ArrowUpRight aria-hidden="true" /></a>)}<button type="button" onClick={() => { setState("idle"); setPlaces([]); }}>{text.again}</button></div>;
  if (state === "location") return <div className={styles.finderNotice}><strong>{text.locationOff}</strong><span>{text.locationHelp}</span><button type="button" onClick={findNearby}><LocateFixed aria-hidden="true" /> {text.retry}</button></div>;
  return <div className={styles.finderAction}><div><span className={styles.momentLabel}>{text.looking.toUpperCase()}</span><div className={styles.momentChoices}><button type="button" className={kind === "restaurant" ? styles.momentActive : ""} onClick={() => { setKind("restaurant"); setState("idle"); }}>{text.food}</button><button type="button" className={kind === "stay" ? styles.momentActive : ""} onClick={() => { setKind("stay"); setState("idle"); }}>{text.stay}</button></div></div>{kind === "restaurant" && <div><span className={styles.momentLabel}>{text.want.toUpperCase()}</span><div className={styles.momentChoices}>{text.options.map((option, index) => <button type="button" className={moment === index ? styles.momentActive : ""} key={option} onClick={() => setMoment(index)}>{option}</button>)}</div></div>}<small className={styles.momentCopy}>{prompt}</small><button type="button" onClick={findNearby} disabled={state === "loading"}><LocateFixed aria-hidden="true" /> {state === "loading" ? text.finding : kind === "stay" ? text.findStays : text.findFood}</button>{state === "empty" ? <small className={styles.finderStatus}>{text.empty}</small> : <small className={styles.finderStatus}>{text.privacy}</small>}</div>;
}
