/**
 * Editorial route knowledge for EasyT.
 *
 * This is deliberately separate from generated itinerary documents. A route is
 * a reusable, reviewable starting point; a trip is the traveller's editable
 * copy. Durations are planning allowances until a live operator feed is wired.
 */
export type RouteRegion = "asia" | "europe" | "south-america" | "central-america" | "north-america" | "africa" | "oceania";
export type RouteInterest = "food" | "culture" | "nature" | "rail" | "coast" | "hiking" | "wildlife" | "heritage";
export type RouteConfidence = "high" | "medium" | "needs-review";

export type RouteConnection = {
  from: string;
  to: string;
  mode: "train" | "bus" | "road" | "ferry" | "flight";
  planningMinutes: number | null;
  note: string;
  confidence: RouteConfidence;
};

export type RouteFamily = {
  key: string;
  title: string;
  region: RouteRegion;
  countries: string[];
  interests: RouteInterest[];
  bestFor: string;
  suggestedDays: { min: number; ideal: number; max: number };
  bases: string[];
  stops: Array<{ name: string; country: string; coordinates: [number, number]; minimumNights: number; reason: string }>;
  connections: RouteConnection[];
  seasonalNotes: string[];
  highlights?: string[];
  sourceLinks: Array<{ label: string; url: string; covers: string }>;
  imageQuery?: string;
  confidence: RouteConfidence;
  reviewedAt: string;
};

const verify = "Verify current schedules, entry rules and opening hours before booking.";

const coreRouteFamilies: RouteFamily[] = [
  {
    key: "japan-slow",
    title: "Japan, one good day at a time",
    region: "asia",
    countries: ["Japan"],
    interests: ["food", "culture", "rail"],
    bestFor: "A first Japan trip with room for neighbourhoods, meals and slower mornings.",
    suggestedDays: { min: 8, ideal: 10, max: 14 },
    bases: ["Tokyo", "Takayama", "Kyoto"],
    stops: [
      { name: "Tokyo", country: "Japan", coordinates: [139.6917, 35.6895], minimumNights: 3, reason: "An energetic opening chapter with enough time to settle in." },
      { name: "Takayama", country: "Japan", coordinates: [137.2523, 36.146], minimumNights: 2, reason: "A smaller mountain base that changes the rhythm between cities." },
      { name: "Kyoto", country: "Japan", coordinates: [135.7681, 35.0116], minimumNights: 3, reason: "A walkable cultural finish that rewards unplanned time." },
    ],
    connections: [
      { from: "Tokyo", to: "Takayama", mode: "train", planningMinutes: 300, note: `Rail and regional connection allowance. ${verify}`, confidence: "medium" },
      { from: "Takayama", to: "Kyoto", mode: "train", planningMinutes: 260, note: `Regional rail connection allowance. ${verify}`, confidence: "medium" },
    ],
    seasonalNotes: ["Spring and autumn are popular and need earlier accommodation planning.", "Summer is hot and humid in cities; keep hiking days flexible."],
    sourceLinks: [
      { label: "Japan Travel", url: "https://www.japan.travel/en/", covers: "Official destination and regional context" },
      { label: "Japan Railways", url: "https://www.japanrailpass-reservation.net/", covers: "Rail planning reference" },
    ],
    confidence: "medium",
    reviewedAt: "2026-08-08",
  },
  {
    key: "taiwan-rail",
    title: "Taiwan by train",
    region: "asia",
    countries: ["Taiwan"],
    interests: ["food", "rail", "culture"],
    bestFor: "Low-friction movement, night markets and a route that keeps changing without changing hotels every night.",
    suggestedDays: { min: 6, ideal: 8, max: 12 },
    bases: ["Taipei", "Taichung", "Tainan"],
    stops: [
      { name: "Taipei", country: "Taiwan", coordinates: [121.5654, 25.033], minimumNights: 3, reason: "A food-led opening with excellent local transport." },
      { name: "Taichung", country: "Taiwan", coordinates: [120.6736, 24.1477], minimumNights: 2, reason: "A useful mid-route pause with arts and tea country nearby." },
      { name: "Tainan", country: "Taiwan", coordinates: [120.227, 22.9997], minimumNights: 2, reason: "A slower, food-first finish." },
    ],
    connections: [{ from: "Taipei", to: "Taichung", mode: "train", planningMinutes: 100, note: `High-speed rail allowance. ${verify}`, confidence: "medium" }, { from: "Taichung", to: "Tainan", mode: "train", planningMinutes: 100, note: `High-speed rail allowance. ${verify}`, confidence: "medium" }],
    seasonalNotes: ["Typhoon season can affect east-coast plans; keep alternatives inland.", "Summer heat and rain favour shorter, neighbourhood-led days."],
    sourceLinks: [{ label: "Taiwan Tourism", url: "https://eng.taiwan.net.tw/", covers: "Official destination context" }, { label: "Taiwan Railways", url: "https://www.railway.gov.tw/tra-tip-web/tip", covers: "Rail operator reference" }],
    confidence: "medium",
    reviewedAt: "2026-08-08",
  },
  {
    key: "andean-highlands",
    title: "Andean highlands, gently",
    region: "south-america",
    countries: ["Peru", "Bolivia"],
    interests: ["nature", "culture", "hiking"],
    bestFor: "Big landscapes with altitude, recovery time and fewer rushed transfers.",
    suggestedDays: { min: 9, ideal: 12, max: 18 },
    bases: ["Cusco", "Sacred Valley", "Arequipa"],
    stops: [
      { name: "Cusco", country: "Peru", coordinates: [-71.9785, -13.517], minimumNights: 3, reason: "Start gently and let the body adjust to altitude." },
      { name: "Sacred Valley", country: "Peru", coordinates: [-72.115, -13.308], minimumNights: 3, reason: "A lower-pressure base for landscapes and heritage sites." },
      { name: "Arequipa", country: "Peru", coordinates: [-71.5375, -16.409], minimumNights: 2, reason: "A lower-key final chapter with a different climate and scale." },
    ],
    connections: [{ from: "Cusco", to: "Sacred Valley", mode: "road", planningMinutes: 120, note: `Road transfer allowance; altitude and traffic can change the day. ${verify}`, confidence: "medium" }, { from: "Sacred Valley", to: "Arequipa", mode: "flight", planningMinutes: 360, note: `Door-to-door flight allowance. ${verify}`, confidence: "needs-review" }],
    seasonalNotes: ["Wet-season conditions can change trekking access and road times.", "Altitude affects pacing; the engine should never promise a strenuous day immediately after arrival."],
    sourceLinks: [{ label: "Peru Travel", url: "https://www.peru.travel/en", covers: "Official destination context" }, { label: "UNESCO World Heritage", url: "https://whc.unesco.org/en/statesparties/pe", covers: "Heritage sites and significance" }],
    confidence: "medium",
    reviewedAt: "2026-08-08",
  },
  {
    key: "portugal-atlantic",
    title: "The Atlantic reset",
    region: "europe",
    countries: ["Portugal"],
    interests: ["coast", "food", "culture"],
    bestFor: "A city-to-coast route with fewer hotel changes and weather-flexible days.",
    suggestedDays: { min: 6, ideal: 7, max: 12 },
    bases: ["Lisbon", "Comporta", "Lagos"],
    stops: [
      { name: "Lisbon", country: "Portugal", coordinates: [-9.1393, 38.7223], minimumNights: 2, reason: "A colourful, walkable opening with food and neighbourhood energy." },
      { name: "Comporta", country: "Portugal", coordinates: [-8.79, 38.38], minimumNights: 2, reason: "A genuine pause between city and coast." },
      { name: "Lagos", country: "Portugal", coordinates: [-8.6742, 37.1028], minimumNights: 2, reason: "Wide-open Atlantic days and a relaxed finish." },
    ],
    connections: [{ from: "Lisbon", to: "Comporta", mode: "road", planningMinutes: 120, note: `Road allowance. ${verify}`, confidence: "medium" }, { from: "Comporta", to: "Lagos", mode: "road", planningMinutes: 240, note: `Road allowance. ${verify}`, confidence: "medium" }],
    seasonalNotes: ["Summer is busier and more expensive along the coast.", "Spring and early autumn often give a better balance of weather and space."],
    sourceLinks: [{ label: "Visit Portugal", url: "https://www.visitportugal.com/en", covers: "Official destination context" }, { label: "Visit Lisboa", url: "https://www.visitlisboa.com/en", covers: "City context" }],
    confidence: "medium",
    reviewedAt: "2026-08-08",
  },
  {
    key: "vietnam-cambodia",
    title: "Vietnam to Angkor, without rushing",
    region: "asia",
    countries: ["Vietnam", "Cambodia"],
    interests: ["food", "culture", "nature"],
    bestFor: "A first Southeast Asia route with street food, river landscapes, and a strong cultural finish.",
    suggestedDays: { min: 12, ideal: 16, max: 22 },
    bases: ["Hanoi", "Hoi An", "Ho Chi Minh City", "Siem Reap"],
    stops: [
      { name: "Hanoi", country: "Vietnam", coordinates: [105.8342, 21.0278], minimumNights: 3, reason: "A lively, food-led opening with a walkable old quarter." },
      { name: "Hoi An", country: "Vietnam", coordinates: [108.338, 15.88], minimumNights: 3, reason: "A slower central base for food, bicycles, and coast time." },
      { name: "Ho Chi Minh City", country: "Vietnam", coordinates: [106.6297, 10.8231], minimumNights: 3, reason: "A high-energy southern chapter before the border crossing." },
      { name: "Siem Reap", country: "Cambodia", coordinates: [103.8564, 13.3633], minimumNights: 3, reason: "A generous base for Angkor rather than a rushed day trip." },
    ],
    connections: [{ from: "Hanoi", to: "Hoi An", mode: "flight", planningMinutes: 240, note: `Domestic flight allowance; compare overnight rail for a slower alternative. ${verify}`, confidence: "medium" }, { from: "Hoi An", to: "Ho Chi Minh City", mode: "flight", planningMinutes: 240, note: `Domestic flight allowance. ${verify}`, confidence: "medium" }, { from: "Ho Chi Minh City", to: "Siem Reap", mode: "flight", planningMinutes: 300, note: `Cross-border flight allowance; confirm entry requirements. ${verify}`, confidence: "needs-review" }],
    seasonalNotes: ["Monsoon patterns vary by coast and region; avoid treating Vietnam as one weather season.", "Angkor is best with early starts and a protected recovery afternoon."],
    sourceLinks: [{ label: "Vietnam Tourism", url: "https://vietnam.travel/", covers: "Official destination context" }, { label: "Visit Cambodia", url: "https://www.tourismcambodia.com/", covers: "Official tourism context" }, { label: "UNESCO Angkor", url: "https://whc.unesco.org/en/list/668/", covers: "Heritage context" }],
    confidence: "needs-review",
    reviewedAt: "2026-08-08",
  },
  {
    key: "colombia-ecuador",
    title: "Colombia to Ecuador, city to cloud forest",
    region: "south-america",
    countries: ["Colombia", "Ecuador"],
    interests: ["culture", "nature", "food", "hiking"],
    bestFor: "A varied Andean route that moves from city energy to coffee country and highland landscapes.",
    suggestedDays: { min: 12, ideal: 16, max: 22 },
    bases: ["Bogotá", "Medellín", "Salento", "Quito"],
    stops: [
      { name: "Bogotá", country: "Colombia", coordinates: [-74.0721, 4.711], minimumNights: 3, reason: "A cultural opening that gives context before smaller places." },
      { name: "Medellín", country: "Colombia", coordinates: [-75.5812, 6.2442], minimumNights: 3, reason: "A warm-weather city base with neighbourhoods and day-trip options." },
      { name: "Salento", country: "Colombia", coordinates: [-75.57, 4.637], minimumNights: 3, reason: "A compact coffee-country base with space for a valley hike." },
      { name: "Quito", country: "Ecuador", coordinates: [-78.4678, -0.1807], minimumNights: 3, reason: "A highland finish that needs a lighter first day at altitude." },
    ],
    connections: [{ from: "Bogotá", to: "Medellín", mode: "flight", planningMinutes: 220, note: `Domestic flight allowance. ${verify}`, confidence: "medium" }, { from: "Medellín", to: "Salento", mode: "road", planningMinutes: 420, note: `Long road transfer allowance; break the journey if needed. ${verify}`, confidence: "needs-review" }, { from: "Salento", to: "Quito", mode: "flight", planningMinutes: 420, note: `Cross-border flight allowance; check routing and entry requirements. ${verify}`, confidence: "needs-review" }],
    seasonalNotes: ["Rain can change mountain-road times; preserve a buffer before flights.", "Quito and nearby highlands require altitude-aware pacing."],
    sourceLinks: [{ label: "Colombia Travel", url: "https://colombia.travel/en", covers: "Official destination context" }, { label: "Ecuador Travel", url: "https://ecuador.travel/en/", covers: "Official destination context" }],
    confidence: "needs-review",
    reviewedAt: "2026-08-08",
  },
  {
    key: "italy-table",
    title: "Italy between tables",
    region: "europe",
    countries: ["Italy"],
    interests: ["food", "culture", "rail"],
    bestFor: "A rail-friendly first Italy route where each base has a distinct appetite and rhythm.",
    suggestedDays: { min: 8, ideal: 12, max: 18 },
    bases: ["Bologna", "Florence", "Rome"],
    stops: [
      { name: "Bologna", country: "Italy", coordinates: [11.3426, 44.4949], minimumNights: 3, reason: "A food-first opening that is easy to explore without rushing." },
      { name: "Florence", country: "Italy", coordinates: [11.2558, 43.7696], minimumNights: 3, reason: "A concentrated cultural chapter with manageable day trips." },
      { name: "Rome", country: "Italy", coordinates: [12.4964, 41.9028], minimumNights: 4, reason: "A high-density finish that deserves protected time." },
    ],
    connections: [{ from: "Bologna", to: "Florence", mode: "train", planningMinutes: 100, note: `High-speed rail allowance. ${verify}`, confidence: "high" }, { from: "Florence", to: "Rome", mode: "train", planningMinutes: 120, note: `High-speed rail allowance. ${verify}`, confidence: "high" }],
    seasonalNotes: ["Spring and autumn offer a better balance of heat and crowd levels.", "Reserve high-demand museums and rail legs around public holidays."],
    sourceLinks: [{ label: "Italia.it", url: "https://www.italia.it/en", covers: "Official destination context" }, { label: "Trenitalia", url: "https://www.trenitalia.com/en.html", covers: "Rail operator reference" }],
    confidence: "high",
    reviewedAt: "2026-08-08",
  },
  {
    key: "balkans-overland",
    title: "The Balkans, one border at a time",
    region: "europe",
    countries: ["Croatia", "Montenegro", "Albania"],
    interests: ["coast", "nature", "culture"],
    bestFor: "A flexible Adriatic route for travellers who want coast, mountains, and fewer predictable city breaks.",
    suggestedDays: { min: 10, ideal: 14, max: 21 },
    bases: ["Dubrovnik", "Kotor", "Shkodër", "Tirana"],
    stops: [
      { name: "Dubrovnik", country: "Croatia", coordinates: [18.0944, 42.6507], minimumNights: 2, reason: "A dramatic coastal opening; use it as a base rather than a checklist." },
      { name: "Kotor", country: "Montenegro", coordinates: [18.7712, 42.4247], minimumNights: 3, reason: "A mountain-and-bay pause with flexible day-trip options." },
      { name: "Shkodër", country: "Albania", coordinates: [19.503, 42.0683], minimumNights: 2, reason: "A softer landing into northern Albania and the mountains." },
      { name: "Tirana", country: "Albania", coordinates: [19.8187, 41.3275], minimumNights: 3, reason: "A lively finish with access to a wider range of day trips." },
    ],
    connections: [{ from: "Dubrovnik", to: "Kotor", mode: "bus", planningMinutes: 180, note: `Border-crossing coach allowance; queues can change the day. ${verify}`, confidence: "needs-review" }, { from: "Kotor", to: "Shkodër", mode: "bus", planningMinutes: 240, note: `Cross-border road allowance. ${verify}`, confidence: "needs-review" }, { from: "Shkodër", to: "Tirana", mode: "bus", planningMinutes: 150, note: `Intercity coach allowance. ${verify}`, confidence: "medium" }],
    seasonalNotes: ["Summer coast demand is high; shoulder season improves flexibility.", "Border crossings need buffer and should not be paired with a fixed timed activity."],
    sourceLinks: [{ label: "Croatia Tourism", url: "https://croatia.hr/en-gb", covers: "Official destination context" }, { label: "Montenegro Travel", url: "https://www.montenegro.travel/en", covers: "Official destination context" }, { label: "Albania Tourism", url: "https://albania.al/", covers: "Official destination context" }],
    confidence: "needs-review",
    reviewedAt: "2026-08-08",
  },
];

const extraRouteFamilies: RouteFamily[] = [
  { key: "thailand-laos", title: "Thailand to Laos, slowly", region: "asia", countries: ["Thailand", "Laos"], interests: ["food", "nature", "culture"], bestFor: "Markets, river towns and a softer overland route through mainland Southeast Asia.", suggestedDays: { min: 10, ideal: 14, max: 20 }, bases: ["Bangkok", "Chiang Mai", "Luang Prabang"], stops: [{ name: "Bangkok", country: "Thailand", coordinates: [100.5018, 13.7563], minimumNights: 3, reason: "A high-energy opening with food and easy onward connections." }, { name: "Chiang Mai", country: "Thailand", coordinates: [98.9853, 18.7883], minimumNights: 3, reason: "A calmer northern base for markets, temples and mountain days." }, { name: "Luang Prabang", country: "Laos", coordinates: [102.135, 19.8856], minimumNights: 3, reason: "A gentle river finish with room to slow down." }], connections: [], seasonalNotes: ["Rain and river conditions vary by month; keep the border day flexible."], sourceLinks: [{ label: "Tourism Thailand", url: "https://www.tourismthailand.org/", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "south-korea", title: "South Korea by rail", region: "asia", countries: ["South Korea"], interests: ["food", "rail", "culture"], bestFor: "Seoul energy, coastal food towns and a simple rail spine.", suggestedDays: { min: 8, ideal: 12, max: 16 }, bases: ["Seoul", "Gyeongju", "Busan"], stops: [{ name: "Seoul", country: "South Korea", coordinates: [126.978, 37.5665], minimumNights: 4, reason: "A deep urban opening with neighbourhoods worth lingering in." }, { name: "Gyeongju", country: "South Korea", coordinates: [129.2247, 35.8562], minimumNights: 2, reason: "A heritage pause between city chapters." }, { name: "Busan", country: "South Korea", coordinates: [129.0756, 35.1796], minimumNights: 3, reason: "A coastal, food-led finish." }], connections: [], seasonalNotes: ["Spring and autumn are popular; reserve rail and stays earlier."], sourceLinks: [{ label: "Visit Korea", url: "https://english.visitkorea.or.kr/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "malaysia-singapore", title: "Malaysia to Singapore, by appetite", region: "asia", countries: ["Malaysia", "Singapore"], interests: ["food", "culture", "coast"], bestFor: "A low-friction food route from street markets to a polished city finish.", suggestedDays: { min: 8, ideal: 11, max: 16 }, bases: ["Kuala Lumpur", "Penang", "Singapore"], stops: [{ name: "Kuala Lumpur", country: "Malaysia", coordinates: [101.6869, 3.139], minimumNights: 3, reason: "A diverse opening that rewards eating across neighbourhoods." }, { name: "Penang", country: "Malaysia", coordinates: [100.3327, 5.4141], minimumNights: 3, reason: "A compact food and heritage base." }, { name: "Singapore", country: "Singapore", coordinates: [103.8198, 1.3521], minimumNights: 3, reason: "A clean, easy final chapter." }], connections: [], seasonalNotes: ["Heat is year-round; plan outdoor days around the morning."], sourceLinks: [{ label: "Malaysia Travel", url: "https://www.malaysia.travel/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "philippines-islands", title: "Philippines, choose your islands", region: "asia", countries: ["Philippines"], interests: ["coast", "nature", "wildlife"], bestFor: "A flexible island route that protects transfer days and leaves room for weather.", suggestedDays: { min: 10, ideal: 14, max: 21 }, bases: ["Manila", "Palawan", "Cebu"], stops: [{ name: "Manila", country: "Philippines", coordinates: [120.9842, 14.5995], minimumNights: 2, reason: "A practical arrival and short cultural opening." }, { name: "Palawan", country: "Philippines", coordinates: [118.7353, 9.8349], minimumNights: 5, reason: "The main nature chapter deserves generous weather buffer." }, { name: "Cebu", country: "Philippines", coordinates: [123.8854, 10.3157], minimumNights: 3, reason: "A flexible finish with coast and onward options." }], connections: [], seasonalNotes: ["Weather can change flights and boats; avoid tight connections."], sourceLinks: [{ label: "Department of Tourism", url: "https://tourism.gov.ph/", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "argentina-chile", title: "Buenos Aires to Patagonia", region: "south-america", countries: ["Argentina", "Chile"], interests: ["nature", "food", "hiking"], bestFor: "Big landscapes balanced with city nights and realistic flight buffers.", suggestedDays: { min: 14, ideal: 18, max: 26 }, bases: ["Buenos Aires", "El Calafate", "Puerto Natales"], stops: [{ name: "Buenos Aires", country: "Argentina", coordinates: [-58.3816, -34.6037], minimumNights: 3, reason: "A generous city opening before the long distances." }, { name: "El Calafate", country: "Argentina", coordinates: [-72.2768, -50.3404], minimumNights: 4, reason: "A practical glacier base with weather room." }, { name: "Puerto Natales", country: "Chile", coordinates: [-72.5286, -51.7236], minimumNights: 4, reason: "A calm staging point for Patagonia days." }], connections: [], seasonalNotes: ["Patagonia is seasonal and windy; protect a spare day before departures."], sourceLinks: [{ label: "Argentina Travel", url: "https://www.argentina.travel/en", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "brazil-coast", title: "Brazil, city to coast", region: "south-america", countries: ["Brazil"], interests: ["coast", "food", "culture"], bestFor: "A warm route that moves from Rio energy to a slower northeast coast.", suggestedDays: { min: 12, ideal: 16, max: 24 }, bases: ["Rio de Janeiro", "Salvador", "Praia do Forte"], stops: [{ name: "Rio de Janeiro", country: "Brazil", coordinates: [-43.1729, -22.9068], minimumNights: 4, reason: "A city chapter with nature built into the edges." }, { name: "Salvador", country: "Brazil", coordinates: [-38.5014, -12.973], minimumNights: 4, reason: "A music, food and history-led middle chapter." }, { name: "Praia do Forte", country: "Brazil", coordinates: [-37.9942, -12.5763], minimumNights: 3, reason: "A beach finish with breathing room." }], connections: [], seasonalNotes: ["Domestic flights are long; avoid stacking them against fixed activities."], sourceLinks: [{ label: "Visit Brasil", url: "https://www.visitbrasil.com/", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "mexico-yucatan", title: "Yucatán, cenotes to coast", region: "central-america", countries: ["Mexico"], interests: ["food", "culture", "coast"], bestFor: "A manageable loop of food, archaeology, swimming and warm evenings.", suggestedDays: { min: 8, ideal: 12, max: 18 }, bases: ["Mérida", "Valladolid", "Tulum"], stops: [{ name: "Mérida", country: "Mexico", coordinates: [-89.5926, 20.9674], minimumNights: 3, reason: "A food and culture base with easy day-trip options." }, { name: "Valladolid", country: "Mexico", coordinates: [-88.2033, 20.6896], minimumNights: 2, reason: "A smaller base for cenotes and heritage." }, { name: "Tulum", country: "Mexico", coordinates: [-87.4654, 20.2114], minimumNights: 3, reason: "A coast finish that can flex with the weather." }], connections: [], seasonalNotes: ["Heat and storms can reshape coast days; keep plans light."], sourceLinks: [{ label: "Visit Mexico", url: "https://visitmexico.com/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "costa-rica-wild", title: "Costa Rica, a softer loop", region: "central-america", countries: ["Costa Rica"], interests: ["nature", "wildlife", "coast"], bestFor: "Volcanoes, rainforest and Pacific time without changing base every day.", suggestedDays: { min: 10, ideal: 14, max: 20 }, bases: ["La Fortuna", "Monteverde", "Santa Teresa"], stops: [{ name: "La Fortuna", country: "Costa Rica", coordinates: [-84.7033, 10.467], minimumNights: 3, reason: "A practical nature opening around the volcano." }, { name: "Monteverde", country: "Costa Rica", coordinates: [-84.8256, 10.3156], minimumNights: 3, reason: "A cooler cloud-forest pause." }, { name: "Santa Teresa", country: "Costa Rica", coordinates: [-85.1347, 9.6539], minimumNights: 4, reason: "A Pacific finish with genuinely open days." }], connections: [], seasonalNotes: ["Road times are slower than the map suggests; preserve transfer buffers."], sourceLinks: [{ label: "Visit Costa Rica", url: "https://www.visitcostarica.com/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "spain-rail", title: "Spain, a rail-shaped appetite", region: "europe", countries: ["Spain"], interests: ["food", "rail", "culture"], bestFor: "A city route where each stop changes the table, light and daily rhythm.", suggestedDays: { min: 10, ideal: 14, max: 20 }, bases: ["Madrid", "Seville", "Barcelona"], stops: [{ name: "Madrid", country: "Spain", coordinates: [-3.7038, 40.4168], minimumNights: 4, reason: "A broad, walkable opening with excellent food." }, { name: "Seville", country: "Spain", coordinates: [-5.9845, 37.3891], minimumNights: 3, reason: "A warmer middle chapter with slower evenings." }, { name: "Barcelona", country: "Spain", coordinates: [2.1734, 41.3851], minimumNights: 4, reason: "A coastal, design-led finish." }], connections: [], seasonalNotes: ["Summer heat can make the south intense; shoulder seasons are easier."], sourceLinks: [{ label: "Spain Travel", url: "https://www.spain.info/en/", covers: "Official destination context" }], confidence: "high", reviewedAt: "2026-08-09" },
  { key: "france-south", title: "France, markets and the south", region: "europe", countries: ["France"], interests: ["food", "coast", "culture"], bestFor: "A relaxed progression from Paris scale to Provence light and Mediterranean evenings.", suggestedDays: { min: 10, ideal: 14, max: 20 }, bases: ["Paris", "Avignon", "Nice"], stops: [{ name: "Paris", country: "France", coordinates: [2.3522, 48.8566], minimumNights: 4, reason: "A dense opening that rewards choosing fewer neighbourhoods." }, { name: "Avignon", country: "France", coordinates: [4.8055, 43.9493], minimumNights: 3, reason: "A useful base for markets and smaller towns." }, { name: "Nice", country: "France", coordinates: [7.262, 43.7102], minimumNights: 3, reason: "A bright coastal finish with easy day trips." }], connections: [], seasonalNotes: ["Rail is strong, but summer demand needs earlier planning."], sourceLinks: [{ label: "France.fr", url: "https://www.france.fr/en/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "greece-islands", title: "Greece, mainland to island", region: "europe", countries: ["Greece"], interests: ["coast", "culture", "food"], bestFor: "Ancient sites, a single island base and a pace that leaves the afternoon open.", suggestedDays: { min: 9, ideal: 13, max: 18 }, bases: ["Athens", "Naxos", "Chania"], stops: [{ name: "Athens", country: "Greece", coordinates: [23.7275, 37.9838], minimumNights: 3, reason: "A cultural opening before the ferry rhythm begins." }, { name: "Naxos", country: "Greece", coordinates: [25.376, 37.1036], minimumNights: 4, reason: "A balanced island base with villages and beaches." }, { name: "Chania", country: "Greece", coordinates: [24.018, 35.5138], minimumNights: 3, reason: "A relaxed Cretan finish." }], connections: [], seasonalNotes: ["Ferries are weather-sensitive; avoid same-day flight connections."], sourceLinks: [{ label: "Visit Greece", url: "https://visitgreece.gr/", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "turkey-coast", title: "Turkey, cities and the Aegean", region: "europe", countries: ["Turkey"], interests: ["food", "coast", "culture"], bestFor: "A generous first look at Istanbul, ancient coast and slower Aegean evenings.", suggestedDays: { min: 10, ideal: 14, max: 21 }, bases: ["Istanbul", "Selçuk", "Bodrum"], stops: [{ name: "Istanbul", country: "Turkey", coordinates: [28.9784, 41.0082], minimumNights: 4, reason: "A huge city that needs protected wandering time." }, { name: "Selçuk", country: "Turkey", coordinates: [27.368, 37.9514], minimumNights: 2, reason: "A practical heritage base away from the coast crowds." }, { name: "Bodrum", country: "Turkey", coordinates: [27.4305, 37.0344], minimumNights: 4, reason: "A sea-led finish with room to do less." }], connections: [], seasonalNotes: ["Summer coast demand is high; spring and autumn are more flexible."], sourceLinks: [{ label: "Go Türkiye", url: "https://goturkiye.com/", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "scotland-islands", title: "Scotland, road and weather", region: "europe", countries: ["United Kingdom"], interests: ["nature", "coast", "hiking"], bestFor: "A weather-aware road route where the landscape is the itinerary.", suggestedDays: { min: 8, ideal: 12, max: 18 }, bases: ["Edinburgh", "Isle of Skye", "Glasgow"], stops: [{ name: "Edinburgh", country: "United Kingdom", coordinates: [-3.1883, 55.9533], minimumNights: 3, reason: "A compact city opening before the road widens." }, { name: "Isle of Skye", country: "United Kingdom", coordinates: [-6.2, 57.3], minimumNights: 4, reason: "A landscape base that needs flexible days." }, { name: "Glasgow", country: "United Kingdom", coordinates: [-4.2518, 55.8642], minimumNights: 2, reason: "A music and food finish with easy departure options." }], connections: [], seasonalNotes: ["Weather can change quickly; never overbook walking days."], sourceLinks: [{ label: "VisitScotland", url: "https://www.visitscotland.com/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "morocco-rail", title: "Morocco, medinas to mountains", region: "africa", countries: ["Morocco"], interests: ["food", "culture", "nature"], bestFor: "A textured route with rail between cities and a deliberate mountain pause.", suggestedDays: { min: 9, ideal: 13, max: 19 }, bases: ["Marrakech", "Fes", "Chefchaouen"], stops: [{ name: "Marrakech", country: "Morocco", coordinates: [-7.5898, 31.6295], minimumNights: 3, reason: "A vivid opening that benefits from one unplanned evening." }, { name: "Fes", country: "Morocco", coordinates: [-5.0078, 34.0181], minimumNights: 3, reason: "A deeper cultural chapter with a different pace." }, { name: "Chefchaouen", country: "Morocco", coordinates: [-5.2636, 35.1714], minimumNights: 2, reason: "A mountain-town pause before the journey home." }], connections: [], seasonalNotes: ["Heat changes the best time of day; keep midday light."], sourceLinks: [{ label: "Visit Morocco", url: "https://www.visitmorocco.com/en", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "south-africa-garden", title: "South Africa, city to garden route", region: "africa", countries: ["South Africa"], interests: ["nature", "wildlife", "coast"], bestFor: "A balanced first route from Cape Town to wildlife and the southern coast.", suggestedDays: { min: 12, ideal: 17, max: 24 }, bases: ["Cape Town", "Hermanus", "Knysna"], stops: [{ name: "Cape Town", country: "South Africa", coordinates: [18.4241, -33.9249], minimumNights: 4, reason: "A rich opening that combines city, food and landscape." }, { name: "Hermanus", country: "South Africa", coordinates: [19.2345, -34.4187], minimumNights: 2, reason: "A coastal wildlife pause." }, { name: "Knysna", country: "South Africa", coordinates: [23.047, -34.0363], minimumNights: 4, reason: "A slower garden-route base with flexible day trips." }], connections: [], seasonalNotes: ["Distances are real; avoid treating the garden route as a quick hop."], sourceLinks: [{ label: "South African Tourism", url: "https://www.southafrica.net/", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
];

const landmarkRouteFamilies: RouteFamily[] = [
  { key: "mexico-guatemala-belize", title: "Maya worlds, three countries", region: "central-america", countries: ["Mexico", "Guatemala", "Belize"], interests: ["heritage", "nature", "coast"], bestFor: "Chichén Itzá, Tikal and Caribbean water in one carefully paced loop.", suggestedDays: { min: 12, ideal: 16, max: 24 }, bases: ["Mérida", "Flores", "Caye Caulker"], stops: [{ name: "Mérida", country: "Mexico", coordinates: [-89.5926, 20.9674], minimumNights: 3, reason: "A strong cultural base for Chichén Itzá and cenotes." }, { name: "Flores", country: "Guatemala", coordinates: [-89.9, 16.93], minimumNights: 4, reason: "A practical base for an unhurried Tikal visit." }, { name: "Caye Caulker", country: "Belize", coordinates: [-88.0283, 17.742], minimumNights: 3, reason: "A low-key reef finish after the inland heat." }], connections: [], seasonalNotes: ["Border crossings and heat need buffer; avoid stacking ruins on transfer days."], highlights: ["Chichén Itzá", "Tikal", "Belize Barrier Reef"], sourceLinks: [{ label: "Mundo Maya", url: "https://www.mundomaya.travel/en", covers: "Regional heritage context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "usa-canada-west", title: "The western parks, two countries", region: "north-america", countries: ["United States", "Canada"], interests: ["nature", "wildlife", "hiking"], bestFor: "A Rockies route connecting Banff, Yellowstone and big landscape days without city hopping.", suggestedDays: { min: 14, ideal: 18, max: 26 }, bases: ["Calgary", "Banff", "Yellowstone"], stops: [{ name: "Calgary", country: "Canada", coordinates: [-114.0719, 51.0447], minimumNights: 2, reason: "A practical arrival before the parks." }, { name: "Banff", country: "Canada", coordinates: [-115.5708, 51.1784], minimumNights: 5, reason: "A generous base for the Canadian Rockies." }, { name: "Yellowstone", country: "United States", coordinates: [-110.5885, 44.428], minimumNights: 5, reason: "A slower wildlife and geothermal chapter." }], connections: [], seasonalNotes: ["Park access and lodging are seasonal; reserve early and protect weather days."], highlights: ["Banff National Park", "Yellowstone National Park", "Grand Prismatic Spring"], sourceLinks: [{ label: "Parks Canada", url: "https://parks.canada.ca/", covers: "Official park context" }, { label: "National Park Service", url: "https://www.nps.gov/", covers: "US park context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "usa-southwest", title: "American Southwest icons", region: "north-america", countries: ["United States"], interests: ["nature", "heritage", "hiking"], bestFor: "Grand Canyon scale, desert light and a road route that earns its distances.", suggestedDays: { min: 8, ideal: 12, max: 18 }, bases: ["Las Vegas", "Grand Canyon", "Moab"], stops: [{ name: "Las Vegas", country: "United States", coordinates: [-115.1398, 36.1699], minimumNights: 1, reason: "A practical gateway rather than the main event." }, { name: "Grand Canyon", country: "United States", coordinates: [-112.1401, 36.0544], minimumNights: 3, reason: "Give the landscape a full day, not a photo stop." }, { name: "Moab", country: "United States", coordinates: [-109.5498, 38.5733], minimumNights: 3, reason: "A base for Arches and Canyonlands." }], connections: [], seasonalNotes: ["Summer heat changes walking plans; shoulder seasons are kinder."], highlights: ["Grand Canyon", "Arches National Park", "Canyonlands"], sourceLinks: [{ label: "Visit the USA", url: "https://www.visittheusa.com/", covers: "Official destination context" }], confidence: "high", reviewedAt: "2026-08-09" },
  { key: "egypt-jordan", title: "Nile to Petra", region: "africa", countries: ["Egypt", "Jordan"], interests: ["heritage", "culture", "nature"], bestFor: "Ancient-world highlights with enough time for Cairo, the Nile and Petra to land.", suggestedDays: { min: 10, ideal: 14, max: 20 }, bases: ["Cairo", "Luxor", "Wadi Musa"], stops: [{ name: "Cairo", country: "Egypt", coordinates: [31.2357, 30.0444], minimumNights: 3, reason: "A high-density opening for the Pyramids and old Cairo." }, { name: "Luxor", country: "Egypt", coordinates: [32.6396, 25.6872], minimumNights: 3, reason: "A river base for the Valley of the Kings." }, { name: "Wadi Musa", country: "Jordan", coordinates: [35.4794, 30.3285], minimumNights: 3, reason: "A proper Petra base rather than a rushed stopover." }], connections: [], seasonalNotes: ["Heat is serious; plan monuments early and protect midday recovery."], highlights: ["Pyramids of Giza", "Valley of the Kings", "Petra"], sourceLinks: [{ label: "Experience Egypt", url: "https://www.experienceegypt.eg/", covers: "Official destination context" }, { label: "Visit Jordan", url: "https://visitjordan.com/", covers: "Official destination context" }], confidence: "needs-review", reviewedAt: "2026-08-09" },
  { key: "india-golden-triangle", title: "India’s golden triangle", region: "asia", countries: ["India"], interests: ["heritage", "food", "culture"], bestFor: "Delhi, Agra and Jaipur with space for the scale and sensory detail.", suggestedDays: { min: 7, ideal: 10, max: 15 }, bases: ["Delhi", "Agra", "Jaipur"], stops: [{ name: "Delhi", country: "India", coordinates: [77.1025, 28.7041], minimumNights: 3, reason: "A layered opening that needs a measured first day." }, { name: "Agra", country: "India", coordinates: [78.0081, 27.1767], minimumNights: 1, reason: "A focused Taj Mahal chapter with an early start." }, { name: "Jaipur", country: "India", coordinates: [75.7873, 26.9124], minimumNights: 3, reason: "A colourful finish with forts, markets and food." }], connections: [], seasonalNotes: ["Heat and traffic reshape timings; keep transfers and monuments separate."], highlights: ["Taj Mahal", "Agra Fort", "Amber Fort"], sourceLinks: [{ label: "Incredible India", url: "https://www.incredibleindia.gov.in/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "italy-greece", title: "Italy to Greece, ancient and alive", region: "europe", countries: ["Italy", "Greece"], interests: ["heritage", "food", "coast"], bestFor: "Rome, Athens and an island finish linked by a clear Mediterranean arc.", suggestedDays: { min: 12, ideal: 16, max: 22 }, bases: ["Rome", "Athens", "Naxos"], stops: [{ name: "Rome", country: "Italy", coordinates: [12.4964, 41.9028], minimumNights: 4, reason: "A major heritage opening that deserves protected time." }, { name: "Athens", country: "Greece", coordinates: [23.7275, 37.9838], minimumNights: 3, reason: "A living city around an ancient centre." }, { name: "Naxos", country: "Greece", coordinates: [25.376, 37.1036], minimumNights: 4, reason: "A restorative island finish." }], connections: [], seasonalNotes: ["Summer ferries and heritage sites are busy; shoulder season improves the shape."], highlights: ["Colosseum", "Acropolis", "Delphi"], sourceLinks: [{ label: "Italia.it", url: "https://www.italia.it/en", covers: "Official destination context" }, { label: "Visit Greece", url: "https://visitgreece.gr/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
  { key: "portugal-spain", title: "Iberia by rail and coast", region: "europe", countries: ["Portugal", "Spain"], interests: ["rail", "food", "coast"], bestFor: "Lisbon, Seville and Barcelona with a route that changes flavour without frantic moves.", suggestedDays: { min: 12, ideal: 16, max: 22 }, bases: ["Lisbon", "Seville", "Barcelona"], stops: [{ name: "Lisbon", country: "Portugal", coordinates: [-9.1393, 38.7223], minimumNights: 4, reason: "A walkable, food-led opening." }, { name: "Seville", country: "Spain", coordinates: [-5.9845, 37.3891], minimumNights: 3, reason: "A warm cultural middle chapter." }, { name: "Barcelona", country: "Spain", coordinates: [2.1734, 41.3851], minimumNights: 4, reason: "A design and coast finish." }], connections: [], seasonalNotes: ["Heat and rail demand rise in summer; plan the south early or late in the day."], highlights: ["Alhambra day trip", "Sagrada Família", "Sintra"], sourceLinks: [{ label: "Visit Portugal", url: "https://www.visitportugal.com/en", covers: "Official destination context" }, { label: "Spain Travel", url: "https://www.spain.info/en/", covers: "Official destination context" }], confidence: "medium", reviewedAt: "2026-08-09" },
];

type RouteSeed = Omit<RouteFamily, "suggestedDays" | "stops" | "connections" | "sourceLinks" | "reviewedAt"> & {
  days: [number, number, number];
  stops: Array<[string, string, [number, number], number, string]>;
  sources?: RouteFamily["sourceLinks"];
};

const seededRoute = ({ days, stops, sources, ...route }: RouteSeed): RouteFamily => ({
  ...route,
  suggestedDays: { min: days[0], ideal: days[1], max: days[2] },
  stops: stops.map(([name, country, coordinates, minimumNights, reason]) => ({ name, country, coordinates, minimumNights, reason })),
  connections: [],
  sourceLinks: sources ?? [],
  reviewedAt: "2026-08-09",
});

// These are deliberately marked needs-review: they are rich route seeds for the
// editorial queue, not claims of live transport or border information.
const globalRouteSeeds: RouteSeed[] = [
  { key: "china-silk-road", title: "China, walls to wild mountains", region: "asia", countries: ["China"], interests: ["heritage", "nature", "food"], bestFor: "Great Wall mornings, Xi’an history and a landscape finish that feels completely different.", days: [10, 14, 20], bases: ["Beijing", "Xi’an", "Zhangjiajie"], stops: [["Beijing", "China", [116.4074, 39.9042], 3, "A layered capital opening with a protected Great Wall day."], ["Xi’an", "China", [108.9398, 34.3416], 3, "A food and heritage base for the Terracotta Army."], ["Zhangjiajie", "China", [110.4792, 29.1171], 3, "A dramatic nature finish with room for weather." ]], seasonalNotes: ["Avoid pairing long intercity movement with major sites."], highlights: ["Great Wall of China", "Terracotta Army", "Zhangjiajie National Forest Park"], imageQuery: "Zhangjiajie China sandstone mountains", confidence: "needs-review" },
  { key: "nepal-bhutan", title: "Himalaya, Nepal to Bhutan", region: "asia", countries: ["Nepal", "Bhutan"], interests: ["nature", "hiking", "culture"], bestFor: "Mountain valleys, living monasteries and a route that takes altitude seriously.", days: [10, 14, 20], bases: ["Kathmandu", "Pokhara", "Paro"], stops: [["Kathmandu", "Nepal", [85.324, 27.7172], 3, "A cultural arrival with time to settle."], ["Pokhara", "Nepal", [83.9856, 28.2096], 3, "A gentler lakeside pause beneath the Annapurnas."], ["Paro", "Bhutan", [89.4125, 27.4305], 3, "A compact Himalayan finish with room for acclimatisation." ]], seasonalNotes: ["Altitude and mountain weather need open days."], highlights: ["Kathmandu Valley", "Annapurna views", "Tiger’s Nest"], imageQuery: "Paro Bhutan Tiger's Nest monastery", confidence: "needs-review" },
  { key: "indonesia-singapore", title: "Java to Singapore, with room to breathe", region: "asia", countries: ["Indonesia", "Singapore"], interests: ["food", "culture", "nature"], bestFor: "Volcanic dawns, temple cities and a practical city finish.", days: [10, 14, 18], bases: ["Yogyakarta", "Ubud", "Singapore"], stops: [["Yogyakarta", "Indonesia", [110.3695, -7.7956], 3, "A heritage and food base for Borobudur and Prambanan."], ["Ubud", "Indonesia", [115.2625, -8.5069], 4, "A greener, slower chapter in central Bali."], ["Singapore", "Singapore", [103.8198, 1.3521], 3, "An easy flight-connected finish." ]], seasonalNotes: ["Build transfer buffers around island flights."], highlights: ["Borobudur", "Prambanan", "Bali rice terraces"], imageQuery: "Borobudur sunrise Indonesia", confidence: "needs-review" },
  { key: "sri-lanka-south-india", title: "Sri Lanka to Kerala", region: "asia", countries: ["Sri Lanka", "India"], interests: ["food", "nature", "culture"], bestFor: "Tea country, heritage rock and a softer South India finish.", days: [12, 16, 22], bases: ["Kandy", "Galle", "Kochi"], stops: [["Kandy", "Sri Lanka", [80.6337, 7.2906], 3, "A hill-country base with rail and tea landscapes nearby."], ["Galle", "Sri Lanka", [80.217, 6.0329], 3, "A relaxed coast chapter after the hills."], ["Kochi", "India", [76.2673, 9.9312], 4, "A food-led Kerala finish with backwater options." ]], seasonalNotes: ["Monsoon patterns differ by coast; check season by month."], highlights: ["Sigiriya", "Kandy to Ella rail", "Fort Kochi"], imageQuery: "Sri Lanka tea train Ella", confidence: "needs-review" },
  { key: "japan-korea-ferries", title: "Japan to Korea, sea and rail", region: "asia", countries: ["Japan", "South Korea"], interests: ["food", "rail", "culture"], bestFor: "A cross-sea route connecting Kyushu food, Busan coast and Seoul energy.", days: [9, 13, 18], bases: ["Fukuoka", "Busan", "Seoul"], stops: [["Fukuoka", "Japan", [130.4017, 33.5904], 3, "A compact, food-forward Kyushu opening."], ["Busan", "South Korea", [129.0756, 35.1796], 3, "A coastal bridge between countries."], ["Seoul", "South Korea", [126.978, 37.5665], 4, "A deep urban finish with strong rail links." ]], seasonalNotes: ["Ferry schedules and sea conditions should be verified."], highlights: ["Fukuoka yatai", "Busan coast", "Seoul palaces"], imageQuery: "Busan South Korea coast skyline", confidence: "needs-review" },
  { key: "mongolia-steppe", title: "Beijing to the Mongolian steppe", region: "asia", countries: ["China", "Mongolia"], interests: ["nature", "culture", "wildlife"], bestFor: "A bold contrast between city scale, grassland and a night under an enormous sky.", days: [10, 14, 19], bases: ["Beijing", "Ulaanbaatar", "Gorkhi-Terelj"], stops: [["Beijing", "China", [116.4074, 39.9042], 3, "A manageable city opening."], ["Ulaanbaatar", "Mongolia", [106.9057, 47.8864], 2, "A practical pause before the landscape."], ["Gorkhi-Terelj", "Mongolia", [107.402, 48.184], 3, "A steppe base for slower nature days." ]], seasonalNotes: ["Short seasons and weather make open days essential."], highlights: ["Gobi gateway", "Gorkhi-Terelj National Park", "Mongolian steppe"], imageQuery: "Mongolia steppe ger mountains", confidence: "needs-review" },
  { key: "australia-new-zealand", title: "Australia to New Zealand, wide open", region: "oceania", countries: ["Australia", "New Zealand"], interests: ["nature", "coast", "hiking"], bestFor: "Harbours, long walks and landscapes that deserve more than a one-night stop.", days: [14, 20, 28], bases: ["Sydney", "Queenstown", "Auckland"], stops: [["Sydney", "Australia", [151.2093, -33.8688], 4, "A city-and-coast opening."], ["Queenstown", "New Zealand", [168.6626, -45.0312], 5, "A nature base with flexible hiking days."], ["Auckland", "New Zealand", [174.7633, -36.8485], 3, "An easy final city chapter." ]], seasonalNotes: ["Distances are large; preserve a rest day after long-haul flights."], highlights: ["Sydney Harbour", "Milford Sound", "New Zealand Southern Alps"], imageQuery: "New Zealand South Island mountains lake", confidence: "needs-review" },
  { key: "peru-bolivia-chile", title: "Andes to Atacama", region: "south-america", countries: ["Peru", "Bolivia", "Chile"], interests: ["nature", "heritage", "hiking"], bestFor: "Machu Picchu, high-altitude cities and desert skies with proper recovery time.", days: [14, 19, 27], bases: ["Cusco", "La Paz", "San Pedro de Atacama"], stops: [["Cusco", "Peru", [-71.9675, -13.5319], 4, "A high-altitude heritage base that rewards going slowly."], ["La Paz", "Bolivia", [-68.1193, -16.4897], 3, "A dramatic urban chapter with altitude-aware pacing."], ["San Pedro de Atacama", "Chile", [-68.2011, -22.9087], 4, "A desert finish for big skies and day trips." ]], seasonalNotes: ["Altitude and border days must stay light."], highlights: ["Machu Picchu", "Uyuni Salt Flats", "Atacama Desert"], imageQuery: "Uyuni Salt Flats Bolivia", confidence: "needs-review" },
  { key: "ecuador-galapagos", title: "Ecuador, Andes to Galápagos", region: "south-america", countries: ["Ecuador"], interests: ["wildlife", "nature", "culture"], bestFor: "Quito depth, cloud forest breathing room and an island wildlife chapter.", days: [10, 14, 20], bases: ["Quito", "Baños", "Santa Cruz"], stops: [["Quito", "Ecuador", [-78.4678, -0.1807], 3, "A highland arrival that needs a measured start."], ["Baños", "Ecuador", [-78.4229, -1.3969], 3, "A greener adventure and waterfall pause."], ["Santa Cruz", "Ecuador", [-90.312, -0.639], 4, "An island base with wildlife-focused day trips." ]], seasonalNotes: ["Island cruises and flights need extra lead time."], highlights: ["Quito historic centre", "Tungurahua landscapes", "Galápagos wildlife"], imageQuery: "Galapagos giant tortoise Ecuador", confidence: "needs-review" },
  { key: "argentina-uruguay", title: "Río de la Plata, slowly", region: "south-america", countries: ["Argentina", "Uruguay"], interests: ["food", "culture", "coast"], bestFor: "Bookshops, long dinners and low-friction river crossings.", days: [7, 10, 15], bases: ["Buenos Aires", "Colonia del Sacramento", "Montevideo"], stops: [["Buenos Aires", "Argentina", [-58.3816, -34.6037], 4, "A city that deserves unstructured afternoons."], ["Colonia del Sacramento", "Uruguay", [-57.8409, -34.4719], 2, "A small, atmospheric pause across the river."], ["Montevideo", "Uruguay", [-56.1645, -34.9011], 3, "A slower coastal capital finish." ]], seasonalNotes: ["Ferry and weekend availability can change the route shape."], highlights: ["Buenos Aires neighbourhoods", "Colonia old town", "Montevideo rambla"], imageQuery: "Colonia del Sacramento Uruguay waterfront", confidence: "needs-review" },
  { key: "panama-colombia", title: "Panama to Colombia, city and Caribbean", region: "south-america", countries: ["Panama", "Colombia"], interests: ["coast", "culture", "food"], bestFor: "Canal scale, Caribbean colour and a Colombian city finish.", days: [9, 13, 18], bases: ["Panama City", "Cartagena", "Medellín"], stops: [["Panama City", "Panama", [-79.5199, 8.9824], 3, "A modern opening with canal context."], ["Cartagena", "Colombia", [-75.4794, 10.391], 3, "A warm, walled-city chapter."], ["Medellín", "Colombia", [-75.5812, 6.2442], 4, "A cooler final city with neighbourhood depth." ]], seasonalNotes: ["Treat cross-border flights as whole travel days."], highlights: ["Panama Canal", "Cartagena old town", "Medellín cable cars"], imageQuery: "Cartagena Colombia colourful old town", confidence: "needs-review" },
  { key: "brazil-argentina", title: "Rio to Iguazú to Buenos Aires", region: "south-america", countries: ["Brazil", "Argentina"], interests: ["nature", "food", "culture"], bestFor: "Beach city energy, a genuine natural wonder and a dinner-led finish.", days: [9, 13, 18], bases: ["Rio de Janeiro", "Foz do Iguaçu", "Buenos Aires"], stops: [["Rio de Janeiro", "Brazil", [-43.1729, -22.9068], 4, "A city framed by mountains and water."], ["Foz do Iguaçu", "Brazil", [-54.5882, -25.5163], 2, "A protected waterfall chapter."], ["Buenos Aires", "Argentina", [-58.3816, -34.6037], 4, "A food and culture finish." ]], seasonalNotes: ["Cross-border waterfall access needs current entry checks."], highlights: ["Christ the Redeemer", "Iguazú Falls", "Buenos Aires tango halls"], imageQuery: "Iguazu Falls Argentina Brazil", confidence: "needs-review" },
  { key: "scandinavia-rail", title: "Scandinavia by rail", region: "europe", countries: ["Denmark", "Sweden", "Norway"], interests: ["rail", "culture", "nature"], bestFor: "Design cities, fjords and a rail route that is part of the experience.", days: [9, 13, 18], bases: ["Copenhagen", "Stockholm", "Oslo"], stops: [["Copenhagen", "Denmark", [12.5683, 55.6761], 3, "A bikeable and design-led opening."], ["Stockholm", "Sweden", [18.0686, 59.3293], 3, "An island city with real neighbourhood depth."], ["Oslo", "Norway", [10.7522, 59.9139], 3, "A calm launch point for the fjord rail line." ]], seasonalNotes: ["Winter daylight changes the rhythm; reserve scenic rail early."], highlights: ["Copenhagen harbour", "Stockholm archipelago", "Norway in a Nutshell corridor"], imageQuery: "Norway fjord train scenery", confidence: "needs-review" },
  { key: "baltics-overland", title: "The Baltics, small capitals and coast", region: "europe", countries: ["Lithuania", "Latvia", "Estonia"], interests: ["culture", "food", "coast"], bestFor: "Three distinct old towns with simple distances and room for Baltic Sea air.", days: [7, 10, 14], bases: ["Vilnius", "Riga", "Tallinn"], stops: [["Vilnius", "Lithuania", [25.2797, 54.6872], 2, "A compact baroque opening."], ["Riga", "Latvia", [24.1052, 56.9496], 3, "An art nouveau and market city chapter."], ["Tallinn", "Estonia", [24.7536, 59.437], 3, "A northern coastal finish." ]], seasonalNotes: ["Summer is light and busy; winter needs a slower outdoor rhythm."], highlights: ["Vilnius old town", "Riga Central Market", "Tallinn medieval centre"], imageQuery: "Tallinn Estonia old town", confidence: "needs-review" },
  { key: "central-europe-rail", title: "Central Europe by rail", region: "europe", countries: ["Czechia", "Austria", "Hungary"], interests: ["rail", "culture", "food"], bestFor: "Three capital cities connected by easy rail and distinct evening rhythms.", days: [8, 12, 16], bases: ["Prague", "Vienna", "Budapest"], stops: [["Prague", "Czechia", [14.4378, 50.0755], 3, "A dense heritage opening worth getting up early for."], ["Vienna", "Austria", [16.3738, 48.2082], 3, "A museum and coffeehouse pause."], ["Budapest", "Hungary", [19.0402, 47.4979], 3, "A river and bathhouse finish." ]], seasonalNotes: ["Rail is easy, but city breaks are busiest around holidays."], highlights: ["Prague historic centre", "Vienna coffeehouses", "Danube in Budapest"], imageQuery: "Budapest Hungary Danube Parliament sunset", confidence: "needs-review" },
  { key: "benelux-rail", title: "Benelux, art and easy trains", region: "europe", countries: ["Netherlands", "Belgium", "Luxembourg"], interests: ["rail", "food", "culture"], bestFor: "Canals, galleries and short connections that leave room for the table.", days: [7, 10, 14], bases: ["Amsterdam", "Antwerp", "Luxembourg City"], stops: [["Amsterdam", "Netherlands", [4.9041, 52.3676], 3, "A water-framed opening with excellent museums."], ["Antwerp", "Belgium", [4.4025, 51.2194], 2, "A more local art and fashion pause."], ["Luxembourg City", "Luxembourg", [6.1319, 49.6116], 2, "A compact final city with valley walks." ]], seasonalNotes: ["Book key museums before weekends and holidays."], highlights: ["Amsterdam canals", "Antwerp old town", "Luxembourg old quarters"], imageQuery: "Amsterdam canal houses evening", confidence: "needs-review" },
  { key: "alps-by-rail", title: "The Alps by rail", region: "europe", countries: ["Switzerland", "Italy", "Austria"], interests: ["rail", "nature", "hiking"], bestFor: "A scenic rail spine through mountain bases that rewards stopping often.", days: [10, 14, 20], bases: ["Lucerne", "St. Moritz", "Innsbruck"], stops: [["Lucerne", "Switzerland", [8.3093, 47.0502], 3, "A lake-and-mountain opening with simple rail access."], ["St. Moritz", "Switzerland", [9.8372, 46.4908], 3, "A high-alpine rail chapter."], ["Innsbruck", "Austria", [11.4041, 47.2692], 3, "A human-scale mountain city finish." ]], seasonalNotes: ["Scenic trains and mountain stays need advance planning in peak season."], highlights: ["Swiss Alps railways", "Bernina corridor", "Tyrol valleys"], imageQuery: "Bernina Express Switzerland train Alps", confidence: "needs-review" },
  { key: "ireland-northern-ireland", title: "Ireland, coast to coast", region: "europe", countries: ["Ireland", "United Kingdom"], interests: ["coast", "nature", "culture"], bestFor: "Pubs, coastal roads and a route shaped by weather rather than rushing.", days: [8, 12, 17], bases: ["Dublin", "Galway", "Belfast"], stops: [["Dublin", "Ireland", [-6.2603, 53.3498], 3, "A literary and food-led opening."], ["Galway", "Ireland", [-9.0568, 53.2707], 3, "A lively west coast base for the Atlantic edge."], ["Belfast", "United Kingdom", [-5.9301, 54.5973], 3, "A compact northern finish with coast access." ]], seasonalNotes: ["Weather is part of the plan; retain flexible coast days."], highlights: ["Cliffs of Moher", "Wild Atlantic Way", "Giant’s Causeway"], imageQuery: "Giant's Causeway Northern Ireland coast", confidence: "needs-review" },
  { key: "slovenia-croatia-italy", title: "Adriatic edges, three countries", region: "europe", countries: ["Slovenia", "Croatia", "Italy"], interests: ["nature", "coast", "food"], bestFor: "Lakes, old ports and a gentle road route across the northern Adriatic.", days: [9, 13, 18], bases: ["Ljubljana", "Split", "Trieste"], stops: [["Ljubljana", "Slovenia", [14.5058, 46.0569], 3, "A compact green capital with lake day trips."], ["Split", "Croatia", [16.4402, 43.5081], 3, "A coast chapter with island options."], ["Trieste", "Italy", [13.7768, 45.6495], 3, "A coffee and sea finish." ]], seasonalNotes: ["Summer roads and ferries need buffers."], highlights: ["Lake Bled", "Diocletian’s Palace", "Trieste waterfront"], imageQuery: "Lake Bled Slovenia sunrise", confidence: "needs-review" },
  { key: "romania-bulgaria-turkey", title: "Balkans to Istanbul", region: "europe", countries: ["Romania", "Bulgaria", "Turkey"], interests: ["culture", "food", "heritage"], bestFor: "A lesser-used overland arc from Transylvanian cities to Istanbul.", days: [10, 14, 20], bases: ["Bucharest", "Sofia", "Istanbul"], stops: [["Bucharest", "Romania", [26.1025, 44.4268], 3, "A lively first chapter with regional rail context."], ["Sofia", "Bulgaria", [23.3219, 42.6977], 2, "A mountain-framed city pause."], ["Istanbul", "Turkey", [28.9784, 41.0082], 4, "A rich final city deserving a slower rhythm." ]], seasonalNotes: ["Cross-border rail and bus timings must be checked before booking."], highlights: ["Transylvanian towns", "Rila Monastery", "Istanbul historic peninsula"], imageQuery: "Istanbul Turkey Bosphorus sunset", confidence: "needs-review" },
  { key: "kenya-tanzania", title: "East Africa, wildlife with space", region: "africa", countries: ["Kenya", "Tanzania"], interests: ["wildlife", "nature", "culture"], bestFor: "Safari landscapes and coast, paced so drives do not swallow the trip.", days: [10, 15, 22], bases: ["Nairobi", "Maasai Mara", "Zanzibar"], stops: [["Nairobi", "Kenya", [36.8219, -1.2921], 2, "A practical arrival and recovery point."], ["Maasai Mara", "Kenya", [35.1439, -1.4061], 3, "A wildlife chapter with protected early starts."], ["Zanzibar", "Tanzania", [39.2026, -6.1659], 4, "A restorative Indian Ocean finish." ]], seasonalNotes: ["Wildlife seasons and domestic connections require current verification."], highlights: ["Maasai Mara", "Serengeti extension", "Stone Town"], imageQuery: "Maasai Mara Kenya safari elephants", confidence: "needs-review" },
  { key: "namibia-botswana-zambia", title: "Desert to delta to falls", region: "africa", countries: ["Namibia", "Botswana", "Zambia"], interests: ["wildlife", "nature", "hiking"], bestFor: "A long-form southern Africa route for travellers who want scale over city hopping.", days: [14, 20, 28], bases: ["Sossusvlei", "Maun", "Livingstone"], stops: [["Sossusvlei", "Namibia", [15.911, -24.727], 3, "A desert base for first-light dunes."], ["Maun", "Botswana", [23.4162, -19.9833], 3, "A gateway to the Okavango Delta."], ["Livingstone", "Zambia", [25.8543, -17.8419], 3, "A Victoria Falls finish with room for weather." ]], seasonalNotes: ["This route relies on flights and long drives; build in recovery days."], highlights: ["Sossusvlei dunes", "Okavango Delta", "Victoria Falls"], imageQuery: "Sossusvlei Namibia dunes sunrise", confidence: "needs-review" },
  { key: "rwanda-uganda", title: "Rwanda and Uganda, green and wild", region: "africa", countries: ["Rwanda", "Uganda"], interests: ["wildlife", "nature", "hiking"], bestFor: "Forest trekking, lake time and a route that treats permits and recovery seriously.", days: [8, 12, 17], bases: ["Kigali", "Volcanoes National Park", "Bwindi"], stops: [["Kigali", "Rwanda", [30.0619, -1.9441], 2, "A thoughtful and easy arrival city."], ["Volcanoes National Park", "Rwanda", [29.517, -1.483], 3, "A permit-led mountain forest chapter."], ["Bwindi", "Uganda", [29.728, -1.07], 3, "A quieter forest base for gorilla trekking." ]], seasonalNotes: ["Permits and border requirements require verified planning before booking."], highlights: ["Volcanoes National Park", "Bwindi Impenetrable Forest", "Lake Kivu"], imageQuery: "Rwanda volcanoes national park gorilla forest", confidence: "needs-review" },
  { key: "ethiopia-kenya", title: "Ethiopia to Kenya, highlands to savannah", region: "africa", countries: ["Ethiopia", "Kenya"], interests: ["heritage", "wildlife", "culture"], bestFor: "Rock-hewn heritage, Rift Valley landscapes and an East Africa wildlife finish.", days: [12, 17, 24], bases: ["Addis Ababa", "Lalibela", "Nairobi"], stops: [["Addis Ababa", "Ethiopia", [38.7578, 8.9806], 2, "A practical highland arrival."], ["Lalibela", "Ethiopia", [39.0406, 12.0316], 3, "A focused heritage base."], ["Nairobi", "Kenya", [36.8219, -1.2921], 3, "A gateway to a final wildlife chapter." ]], seasonalNotes: ["Use current official travel and entry guidance for every border and flight."], highlights: ["Lalibela rock-hewn churches", "Great Rift Valley", "Nairobi National Park"], imageQuery: "Lalibela Ethiopia rock hewn churches", confidence: "needs-review" },
  { key: "canada-atlantic", title: "Atlantic Canada, harbour to highlands", region: "north-america", countries: ["Canada"], interests: ["coast", "nature", "food"], bestFor: "Seafood, coastal roads and a slower road trip through the east.", days: [8, 12, 17], bases: ["Halifax", "Cape Breton", "Charlottetown"], stops: [["Halifax", "Canada", [-63.5752, 44.6488], 3, "A harbour city opening with food and music."], ["Cape Breton", "Canada", [-60.75, 46.2], 3, "A coastal highlands chapter with weather room."], ["Charlottetown", "Canada", [-63.1311, 46.2382], 2, "A gentle island finish." ]], seasonalNotes: ["Road conditions and seasonal openings change the ideal timing."], highlights: ["Cabot Trail", "Bay of Fundy", "Prince Edward Island coast"], imageQuery: "Cabot Trail Nova Scotia Canada coast", confidence: "needs-review" },
  { key: "new-england-quebec", title: "New England to Québec", region: "north-america", countries: ["United States", "Canada"], interests: ["food", "culture", "nature"], bestFor: "Autumn colour, small cities and a cross-border route full of good tables.", days: [7, 11, 16], bases: ["Boston", "Burlington", "Québec City"], stops: [["Boston", "United States", [-71.0589, 42.3601], 3, "A historic and walkable opening."], ["Burlington", "United States", [-73.2121, 44.4759], 2, "A lake and foliage pause."], ["Québec City", "Canada", [-71.208, 46.8139], 3, "A distinct old-city finish." ]], seasonalNotes: ["Autumn weekends fill early; borders require current entry checks."], highlights: ["Boston Freedom Trail", "Vermont foliage", "Québec old town"], imageQuery: "Quebec City Canada old town autumn", confidence: "needs-review" },
  { key: "pacific-northwest", title: "Pacific Northwest, city to island", region: "north-america", countries: ["United States", "Canada"], interests: ["nature", "food", "coast"], bestFor: "Coffee, forests, ferries and a city route that keeps the water close.", days: [8, 12, 17], bases: ["Seattle", "Olympic Peninsula", "Vancouver"], stops: [["Seattle", "United States", [-122.3321, 47.6062], 3, "A food and neighbourhood-led opening."], ["Olympic Peninsula", "United States", [-123.6044, 47.8021], 3, "A wild coast pause with flexible weather days."], ["Vancouver", "Canada", [-123.1207, 49.2827], 3, "A mountain-and-water final city." ]], seasonalNotes: ["Ferries and mountain conditions need buffers."], highlights: ["Olympic National Park", "Pacific coast", "Stanley Park"], imageQuery: "Olympic National Park Washington coast", confidence: "needs-review" },
  { key: "california-baja", title: "California to Baja, by the coast", region: "north-america", countries: ["United States", "Mexico"], interests: ["coast", "food", "nature"], bestFor: "Pacific road time, Mexican food and a route that gets better when it slows down.", days: [8, 12, 18], bases: ["Los Angeles", "San Diego", "Ensenada"], stops: [["Los Angeles", "United States", [-118.2437, 34.0522], 2, "A practical arrival and city opening."], ["San Diego", "United States", [-117.1611, 32.7157], 3, "A warm border-city pause."], ["Ensenada", "Mexico", [-116.6, 31.8667], 3, "A Baja food and coast finish." ]], seasonalNotes: ["Border waits and driving conditions need real buffers."], highlights: ["Big Sur extension", "San Diego coast", "Valle de Guadalupe"], imageQuery: "Baja California Mexico coast Ensenada", confidence: "needs-review" },
  { key: "cuba-mexico", title: "Havana to the Yucatán", region: "north-america", countries: ["Cuba", "Mexico"], interests: ["culture", "food", "coast"], bestFor: "Music, colour and a Caribbean-to-Maya route with two very different rhythms.", days: [10, 14, 20], bases: ["Havana", "Trinidad", "Mérida"], stops: [["Havana", "Cuba", [-82.3666, 23.1136], 4, "A city best explored slowly and on foot."], ["Trinidad", "Cuba", [-79.9847, 21.801], 3, "A smaller colonial and coast chapter."], ["Mérida", "Mexico", [-89.5926, 20.9674], 3, "A Yucatán food and heritage finish." ]], seasonalNotes: ["Entry requirements and flight routes need verified planning."], highlights: ["Old Havana", "Trinidad de Cuba", "Chichén Itzá"], imageQuery: "Havana Cuba colourful classic cars", confidence: "needs-review" },
  { key: "guatemala-honduras-el-salvador", title: "Central America, volcanoes and Maya worlds", region: "central-america", countries: ["Guatemala", "Honduras", "El Salvador"], interests: ["heritage", "nature", "culture"], bestFor: "Antigua, Copán and volcanic lakes with enough room for border realities.", days: [10, 14, 20], bases: ["Antigua Guatemala", "Copán Ruinas", "Santa Ana"], stops: [["Antigua Guatemala", "Guatemala", [-90.7339, 14.5586], 3, "A walkable colonial opening with volcano views."], ["Copán Ruinas", "Honduras", [-89.142, 15.268], 2, "A focused Maya heritage stop."], ["Santa Ana", "El Salvador", [-89.5597, 13.9942], 3, "A flexible base for crater-lake and coffee-country days." ]], seasonalNotes: ["Verify border rules and transfers before committing to onward travel."], highlights: ["Antigua Guatemala", "Copán", "Santa Ana Volcano"], imageQuery: "Antigua Guatemala volcano colonial streets", confidence: "needs-review" },
  { key: "southeast-asia-backpacker-loop", title: "Southeast Asia, the classic overland loop", region: "asia", countries: ["Thailand", "Laos", "Vietnam", "Cambodia"], interests: ["food", "culture", "nature"], bestFor: "A properly paced version of the classic backpacker circuit, with temples, river travel and room to choose your own pace.", days: [21, 30, 45], bases: ["Bangkok", "Luang Prabang", "Hanoi", "Siem Reap"], stops: [["Bangkok", "Thailand", [100.5018, 13.7563], 3, "A practical international gateway with a food-led opening."], ["Luang Prabang", "Laos", [102.135, 19.885], 3, "A slower river chapter between bigger cities."], ["Hanoi", "Vietnam", [105.8342, 21.0278], 4, "A layered northern base with time for food and nearby landscapes."], ["Siem Reap", "Cambodia", [103.8558, 13.3633], 3, "A protected heritage finish for Angkor rather than a rushed day trip."]], seasonalNotes: ["This is a flexible route family, not a fixed border sequence. Check current entry rules and transport before committing."], highlights: ["Bangkok street food", "Mekong river travel", "Hanoi old quarter", "Angkor"], imageQuery: "Luang Prabang Laos Mekong river temple", sources: [{ label: "Classic Southeast Asia route context", url: "https://trail.bananabackpacks.com/banana-pancake-trail/", covers: "Editorial backpacker-trail reference" }], confidence: "needs-review" },
  { key: "central-asia-silk-road", title: "Central Asia, Silk Road to high mountains", region: "asia", countries: ["Uzbekistan", "Kyrgyzstan", "Kazakhstan"], interests: ["heritage", "nature", "culture"], bestFor: "Silk Road cities, mountain lakes and a more demanding multi-country route with real cultural contrast.", days: [14, 20, 30], bases: ["Tashkent", "Samarkand", "Bishkek", "Almaty"], stops: [["Tashkent", "Uzbekistan", [69.2401, 41.2995], 2, "A connected first city before moving through the Silk Road core."], ["Samarkand", "Uzbekistan", [66.9597, 39.6542], 3, "A major heritage chapter that deserves time beyond the Registan."], ["Bishkek", "Kyrgyzstan", [74.5698, 42.8746], 2, "A practical mountain gateway with room for a reset."], ["Almaty", "Kazakhstan", [76.886, 43.2389], 3, "A city-and-mountains finish with strong regional connections."]], seasonalNotes: ["Border, visa and high-pass conditions are volatile. Verify each leg with official sources before booking."], highlights: ["Samarkand", "Tien Shan landscapes", "Issyk-Kul extension", "Almaty"], imageQuery: "Samarkand Uzbekistan Registan square", sources: [{ label: "Visit Kyrgyzstan Central Asia itinerary", url: "https://www.visitkyrgyzstan.org/central-asia-itinerary/", covers: "Multi-country Central Asia route context" }, { label: "Kazakh Travel multi-country routes", url: "https://www.kazakh.travel/en/blog/central-asia-tours", covers: "Regional itinerary context" }], confidence: "needs-review" },
  { key: "caucasus-crossroads", title: "The Caucasus, mountains and table culture", region: "asia", countries: ["Georgia", "Armenia", "Azerbaijan"], interests: ["culture", "food", "nature"], bestFor: "Wine country, mountain roads and three distinct cultures, built with flexibility around changing border realities.", days: [12, 18, 26], bases: ["Tbilisi", "Yerevan", "Baku"], stops: [["Tbilisi", "Georgia", [44.793, 41.7151], 4, "A generous opening for food, wine and day trips."], ["Yerevan", "Armenia", [44.4991, 40.1792], 3, "A compact city base for temples and highland roads."], ["Baku", "Azerbaijan", [49.8671, 40.4093], 3, "A Caspian finish treated as a separately verified chapter."]], seasonalNotes: ["Do not assume a direct Armenia-Azerbaijan crossing. Build this as connected, independently verified legs via current official guidance."], highlights: ["Tbilisi old town", "Armenian highlands", "Baku old city"], imageQuery: "Tbilisi Georgia old town mountains", sources: [{ label: "Armenia travel planning", url: "https://armenia.travel/plan-your-trip/flights-visa/", covers: "Official entry and border context" }, { label: "Azerbaijan western route", url: "https://azerbaijan.travel/western-route", covers: "Official Azerbaijan route context" }], confidence: "needs-review" },
  { key: "central-america-southbound", title: "Central America, Guatemala to Panama", region: "central-america", countries: ["Guatemala", "Nicaragua", "Costa Rica", "Panama"], interests: ["nature", "coast", "culture"], bestFor: "Volcanoes, colonial cities and Caribbean water on the southbound stretch many long-term travellers shape around the weather.", days: [18, 28, 42], bases: ["Antigua Guatemala", "León", "La Fortuna", "Bocas del Toro"], stops: [["Antigua Guatemala", "Guatemala", [-90.7339, 14.5586], 3, "A compact first base with volcano and market days."], ["León", "Nicaragua", [-86.878, 12.4357], 3, "A colonial and volcano chapter with recovery time."], ["La Fortuna", "Costa Rica", [-84.6453, 10.4711], 3, "A rainforest base with room for wet-weather shifts."], ["Bocas del Toro", "Panama", [-82.244, 9.34], 4, "An island finish where buffers matter more than a rigid schedule."]], seasonalNotes: ["Treat border days as light days and verify country-specific entry requirements before travel."], highlights: ["Antigua", "Nicaragua volcanoes", "Arenal", "Bocas del Toro"], imageQuery: "Bocas del Toro Panama Caribbean island", sources: [{ label: "Mundo Maya", url: "https://www.mundomaya.travel/en", covers: "Central America destination context" }], confidence: "needs-review" },
  { key: "australia-east-coast", title: "Australia’s East Coast, Sydney to Cairns", region: "oceania", countries: ["Australia"], interests: ["coast", "nature", "wildlife"], bestFor: "Surf towns, reef days and a classic long-haul backpacker route that needs fewer stops than the map suggests.", days: [12, 18, 28], bases: ["Sydney", "Byron Bay", "Airlie Beach", "Cairns"], stops: [["Sydney", "Australia", [151.2093, -33.8688], 3, "A city-and-coast opening before the route turns north."], ["Byron Bay", "Australia", [153.602, -28.6474], 3, "A slower beach chapter with room to recover."], ["Airlie Beach", "Australia", [148.718, -20.2678], 3, "A practical Whitsundays base, not just a transfer night."], ["Cairns", "Australia", [145.7781, -16.9186], 4, "A tropical finish for reef and rainforest days."]], seasonalNotes: ["Distances and wet-season patterns should guide the direction and timing of the route."], highlights: ["Byron Bay", "Whitsundays", "Great Barrier Reef"], imageQuery: "Whitsundays Australia aerial beach", sources: [{ label: "Tourism Australia East Coast itinerary", url: "https://www.australia.com/en/trips-and-itineraries/sydney-and-surrounds/sydney-to-cairns-australia-east-coast-itinerary.html", covers: "Official Sydney-to-Cairns route context" }], confidence: "needs-review" },
  { key: "iceland-ring-road", title: "Iceland’s Ring Road, slowly", region: "europe", countries: ["Iceland"], interests: ["nature", "coast", "hiking"], bestFor: "Waterfalls, black-sand beaches and long light, paced so the drive does not take over the whole trip.", days: [7, 10, 15], bases: ["Reykjavík", "Vík", "Mývatn", "Akureyri"], stops: [["Reykjavík", "Iceland", [-21.9426, 64.1466], 2, "A soft arrival before the road opens out."], ["Vík", "Iceland", [-19.0083, 63.4189], 2, "A south-coast base for waterfalls and black-sand beaches."], ["Mývatn", "Iceland", [-16.9969, 65.603], 2, "A northern volcanic landscape chapter."], ["Akureyri", "Iceland", [-18.0907, 65.6885], 2, "A slower north-coast finish before returning west."]], seasonalNotes: ["Road, weather and daylight conditions drive this route. Keep nightly stays flexible where possible."], highlights: ["South Coast waterfalls", "Jökulsárlón", "Mývatn", "Eastfjords"], imageQuery: "Iceland Ring Road black sand beach waterfall", sources: [{ label: "Visit Iceland Ring Road", url: "https://www.visiticeland.com/article/the-ring-road/", covers: "Official Ring Road context" }], confidence: "needs-review" },
  { key: "camino-frances", title: "Camino Francés, one town at a time", region: "europe", countries: ["France", "Spain"], interests: ["hiking", "culture", "heritage"], bestFor: "A major walking route for travellers who want a physical journey with a clear daily rhythm and no need to invent the spine.", days: [18, 35, 45], bases: ["Saint-Jean-Pied-de-Port", "Burgos", "León", "Santiago de Compostela"], stops: [["Saint-Jean-Pied-de-Port", "France", [-1.2378, 43.1638], 1, "A natural beginning before the Pyrenees."], ["Burgos", "Spain", [-3.6969, 42.3439], 2, "A recovery and heritage chapter on the central plateau."], ["León", "Spain", [-5.5703, 42.5987], 2, "A city pause before the final western stretch."], ["Santiago de Compostela", "Spain", [-8.5448, 42.8805], 2, "A finish that benefits from an unhurried arrival day."]], seasonalNotes: ["Accommodation, weather and daily walking capacity should drive the itinerary more than a fixed pace."], highlights: ["Pyrenees crossing", "Burgos Cathedral", "León", "Santiago de Compostela"], imageQuery: "Camino de Santiago Spain pilgrims trail", sources: [{ label: "Galicia Camino de Santiago", url: "https://www.camino.xacobeo.gal/en/routes", covers: "Official route context" }], confidence: "needs-review" },
  { key: "tour-du-mont-blanc", title: "Tour du Mont Blanc, three countries", region: "europe", countries: ["France", "Italy", "Switzerland"], interests: ["hiking", "nature", "culture"], bestFor: "An iconic alpine circuit with a meaningful cross-border shape, where weather and refuge availability set the real pace.", days: [8, 11, 15], bases: ["Les Houches", "Courmayeur", "Champex-Lac"], stops: [["Les Houches", "France", [6.7926, 45.89], 1, "A straightforward start and finish base near Chamonix."], ["Courmayeur", "Italy", [6.9705, 45.7926], 2, "A restorative Italian valley chapter."], ["Champex-Lac", "Switzerland", [7.1174, 46.0288], 1, "A quieter lake stop on the Swiss section."]], seasonalNotes: ["Snow, weather, refuge bookings and walking ability are core route inputs, not minor details."], highlights: ["Mont Blanc massif", "Courmayeur", "Swiss alpine valleys"], imageQuery: "Tour du Mont Blanc alpine trail France Italy Switzerland", sources: [{ label: "Tour du Mont Blanc official", url: "https://www.autourdumontblanc.com/en/", covers: "Official trek context" }], confidence: "needs-review" },
  { key: "inca-trail-sacred-valley", title: "Cusco, Sacred Valley and Machu Picchu", region: "south-america", countries: ["Peru"], interests: ["heritage", "hiking", "culture"], bestFor: "A more thoughtful Machu Picchu route that gives altitude, the Sacred Valley and the trek equal weight.", days: [7, 10, 14], bases: ["Cusco", "Ollantaytambo", "Aguas Calientes"], stops: [["Cusco", "Peru", [-71.9675, -13.5319], 3, "A protected altitude-adjustment opening."], ["Ollantaytambo", "Peru", [-72.264, -13.2586], 2, "A Sacred Valley base that takes pressure off the Machu Picchu day."], ["Aguas Calientes", "Peru", [-72.545, -13.154], 1, "A focused final night for a calmer early entry."]], seasonalNotes: ["Permits, altitude and seasonal trail conditions require early, verified planning."], highlights: ["Cusco", "Sacred Valley", "Machu Picchu"], imageQuery: "Machu Picchu Peru sunrise", sources: [{ label: "Peru Travel", url: "https://www.peru.travel/en", covers: "Official Peru destination context" }], confidence: "needs-review" },
  { key: "patagonia-w-circuit", title: "Patagonia, the W and beyond", region: "south-america", countries: ["Chile", "Argentina"], interests: ["hiking", "nature", "wildlife"], bestFor: "A flagship Patagonian trek with a slower Argentine finish, built around weather and reservation realities.", days: [10, 14, 20], bases: ["Puerto Natales", "Torres del Paine", "El Calafate", "El Chaltén"], stops: [["Puerto Natales", "Chile", [-72.505, -51.7236], 2, "A vital gear and weather buffer before the park."], ["Torres del Paine", "Chile", [-73.0243, -51.253], 4, "The route’s central walking chapter, paced around the W Circuit."], ["El Calafate", "Argentina", [-72.2768, -50.3379], 2, "A recovery stop with glacier access."], ["El Chaltén", "Argentina", [-72.8858, -49.3315], 3, "A final hiking base that benefits from weather flexibility."]], seasonalNotes: ["Refuges, campsites, wind and transport should be validated before the route is sold as available."], highlights: ["Torres del Paine W Trek", "Perito Moreno Glacier", "Fitz Roy"], imageQuery: "Torres del Paine Patagonia W Trek mountains", sources: [{ label: "Chile Travel W Trek", url: "https://chile.travel/en/itineraries/torres-del-paine-w-trek-the-definitive-guide/", covers: "Official W Trek context" }], confidence: "needs-review" },
  { key: "north-india-backpacker-loop", title: "North India, rivers, desert and cities", region: "asia", countries: ["India"], interests: ["food", "culture", "heritage"], bestFor: "A broader north India route that moves from Delhi’s intensity to Rishikesh, Varanasi and Rajasthan without pretending the distances are small.", days: [14, 21, 30], bases: ["Delhi", "Rishikesh", "Varanasi", "Jaipur"], stops: [["Delhi", "India", [77.1025, 28.7041], 3, "A high-intensity start that needs a slow first day."], ["Rishikesh", "India", [78.2676, 30.0869], 3, "A river and foothills pause after the capital."], ["Varanasi", "India", [82.9739, 25.3176], 3, "A culturally dense chapter best approached with time and care."], ["Jaipur", "India", [75.7873, 26.9124], 3, "A food and fort finish after longer rail distances."]], seasonalNotes: ["Heat, rail availability and festival dates materially change the right shape for this trip."], highlights: ["Old Delhi", "Ganges in Varanasi", "Rajasthan forts"], imageQuery: "Varanasi India Ganges sunrise boats", sources: [{ label: "Incredible India", url: "https://www.incredibleindia.gov.in/", covers: "Official India destination context" }], confidence: "needs-review" },
  { key: "mexico-oaxaca-chiapas", title: "Mexico City to Guatemala, food and Maya highlands", region: "central-america", countries: ["Mexico", "Guatemala"], interests: ["food", "culture", "heritage"], bestFor: "A classic southbound Mexico route that links capital energy, Oaxaca food culture and Maya highlands before Guatemala.", days: [12, 18, 26], bases: ["Mexico City", "Oaxaca", "San Cristóbal de las Casas", "Antigua Guatemala"], stops: [["Mexico City", "Mexico", [-99.1332, 19.4326], 4, "A museum, neighbourhood and food opening worth protecting."], ["Oaxaca", "Mexico", [-96.7266, 17.0732], 4, "A market and mezcal chapter with enough time to eat widely."], ["San Cristóbal de las Casas", "Mexico", [-92.6376, 16.737], 3, "A highland transition before the border."], ["Antigua Guatemala", "Guatemala", [-90.7339, 14.5586], 3, "A clear colonial and volcanic finish."]], seasonalNotes: ["Build border and mountain-road buffers into the plan, particularly in wet season."], highlights: ["Mexico City museums", "Oaxaca markets", "Maya highlands", "Antigua"], imageQuery: "Oaxaca Mexico colourful market streets", sources: [{ label: "Visit Mexico", url: "https://visitmexico.com/", covers: "Official Mexico destination context" }], confidence: "needs-review" },
  { key: "south-africa-cape-to-kruger", title: "South Africa, Cape Town to Kruger", region: "africa", countries: ["South Africa"], interests: ["wildlife", "coast", "food"], bestFor: "A useful first South Africa route that gives Cape Town, the Garden Route and a wildlife finish their own space.", days: [10, 15, 22], bases: ["Cape Town", "Knysna", "Kruger National Park"], stops: [["Cape Town", "South Africa", [18.4241, -33.9249], 4, "A city-and-mountain opening with enough room for weather."], ["Knysna", "South Africa", [23.047, -34.036], 3, "A Garden Route base rather than a string of one-night coastal stops."], ["Kruger National Park", "South Africa", [31.485, -24.994], 4, "A wildlife finish that needs early starts and recovery time."]], seasonalNotes: ["Safari availability, self-drive conditions and internal flights should be confirmed before booking."], highlights: ["Cape Town", "Garden Route", "Kruger National Park"], imageQuery: "Kruger National Park South Africa elephant safari", sources: [{ label: "South African Tourism", url: "https://www.southafrica.net/", covers: "Official destination context" }], confidence: "needs-review" },
];

const globalRouteFamilies: RouteFamily[] = globalRouteSeeds.map(seededRoute);

export const routeFamilies: RouteFamily[] = [...coreRouteFamilies, ...extraRouteFamilies, ...landmarkRouteFamilies, ...globalRouteFamilies];

export const routeFamilyByKey = Object.fromEntries(routeFamilies.map((route) => [route.key, route]));

export function scoreRouteFamily(route: RouteFamily, input: { days?: number; interests?: RouteInterest[]; region?: RouteRegion }) {
  const interestMatches = input.interests?.filter((interest) => route.interests.includes(interest)).length ?? 0;
  const dayFit = input.days === undefined ? 0 : input.days >= route.suggestedDays.min && input.days <= route.suggestedDays.max ? 2 : -1;
  const regionFit = input.region && input.region !== route.region ? -2 : 0;
  return interestMatches * 2 + dayFit + regionFit + (route.confidence === "high" ? 1 : 0);
}

export function recommendRouteFamilies(input: Parameters<typeof scoreRouteFamily>[1]) {
  return [...routeFamilies].sort((a, b) => scoreRouteFamily(b, input) - scoreRouteFamily(a, input));
}
